# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx1G
# Fabric Properties
# check these on https://fabricmc.net/develop
minecraft_version=26.2
loader_version=0.19.3
loom_version=1.17-SNAPSHOT

# Mod Properties
mod_version=3.4.1
archives_base_name=krysztal-language-scala
description=Krysztal's fork of fabric language module for Scala.
url=https://github.com/Krysztal112233/krysztal-language-scala/

# Scala
scala_version=3.4.0
